POST http://127.0.0.1:8080/webhook
Content-Type: application/json
User-Agent: GitLab/16.11.2-ee
X-Gitlab-Event: Push Hook
X-Gitlab-Webhook-UUID: 4934cc87-96a7-401b-8256-4aa3ea1c8f74
X-Gitlab-Instance: https://gitlab.com
X-Gitlab-Token: [REDACTED]
X-Gitlab-Event-UUID: 04862d56-febc-4be8-8339-be10e5120f02
X-Nuecagram-Token: {{X-Nuecagram-Token}}
X-Nuecagram-Chat-Id: {{X-Nuecagram-Chat-Id}}
X-Nuecagram-Topic-Id: {{X-Nuecagram-Topic-Id}}

{
  "object_kind": "push",
  "event_name": "push",
  "before": "20f73df08b2fe02c5a8a9e77b445df69fab96f15",
  "after": "0000000000000000000000000000000000000000",
  "ref": "refs/heads/test-branch",
  "ref_protected": false,
  "checkout_sha": "20f73df08b2fe02c5a8a9e77b445df69fab96f15",
  "message": null,
  "user_id": 38,
  "user_name": "raquezha",
  "user_username": "raquezha",
  "user_email": "[REDACTED]",
  "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/38/avatar.png",
  "project_id": 105,
  "project": {
    "id": 105,
    "name": "🤖customer-app-customer-app",
    "description": "This is awesome"
    "web_url": "https://gitlab.com/android-team/customer-app",
    "avatar_url": "https://gitlab.com/uploads/-/system/project/avatar/105/photo_2023-09-26_14-46-04_Background_Removed.png",
    "git_ssh_url": "git@gitlab.com:android-team/customer-app.git",
    "git_http_url": "https://gitlab.com/android-team/customer-app.git",
    "namespace": "customer-app",
    "visibility_level": 0,
    "path_with_namespace": "android-team/customer-app",
    "default_branch": "main",
    "ci_config_path": null,
    "homepage": "https://gitlab.com/android-team/customer-app",
    "url": "git@gitlab.com:android-team/customer-app.git",
    "ssh_url": "git@gitlab.com:android-team/customer-app.git",
    "http_url": "https://gitlab.com/android-team/customer-app.git"
  },
  "commits": [

  ],
  "total_commits_count": 0,
  "push_options": {
  },
  "repository": {
    "name": "🤖customer-app-customer-app",
    "url": "git@gitlab.com:android-team/customer-app.git",
    "description": "This is awesome"
    "homepage": "https://gitlab.com/android-team/customer-app",
    "git_http_url": "https://gitlab.com/android-team/customer-app.git",
    "git_ssh_url": "git@gitlab.com:android-team/customer-app.git",
    "visibility_level": 0
  }
}
###
