name: Dependency Scan

on: [workflow_call, push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          vuln-type: library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'
