name: Run Tests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on: [workflow_call, push, pull_request, workflow_dispatch]

jobs:
  test:
    uses: ./.github/workflows/setup-gradle.yml
    with:
      gradle-task: test
